name: nomac
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.13.4 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.0
  pedantic: ^1.11.1
dependencies:
  args: ^2.2.0
  dotenv: ^3.0.0
  get_it: ^7.2.0
  json_serializable: ^5.0.0
  logging: ^1.0.1
  mongo_dart: ^0.7.1
  nyxx: ^2.0.0-rc.12
  nyxx_interactions: ^2.0.0-rc.17
  path: ^1.8.0
